HF-ADS7952 Driver: ads7952::reg::Response Namespace Reference
ads7952::reg::Response Namespace Reference
ADS7952 Driver » Register and Frame Constants
Functions
constexpr uint8_t GetChannel (uint16_t frame) noexcept
Extract channel descriptor from response frame DO[15:12].
constexpr uint16_t GetData (uint16_t frame) noexcept
Extract conversion data from response frame DO[11:0].
Function Documentation
GetChannel()
constexpr uint8_t ads7952::reg::Response::GetChannel (uint16_t frame) inline constexpr noexcept
Extract channel descriptor from response frame DO[15:12].
Parameters
frame 16-bit ADC response frame.
Returns
Reported channel index.
Definition at line 213 of file ads7952_registers.hpp.
Referenced by ads7952::ADS7952< SpiType >::ReadAllChannels(), and ads7952::ADS7952< SpiType >::ReadChannel().
GetData()
constexpr uint16_t ads7952::reg::Response::GetData (uint16_t frame) inline constexpr noexcept
Extract conversion data from response frame DO[11:0].
Parameters
frame 16-bit ADC response frame.
Returns
Raw 12-bit conversion value.
Definition at line 221 of file ads7952_registers.hpp.
Referenced by ads7952::ADS7952< SpiType >::ReadAllChannels(), and ads7952::ADS7952< SpiType >::ReadChannel().